add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration
$character
"""

[directory]
style = "bold purple"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold cyan"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 1000
format = "took [$duration](yellow)"
style = "yellow"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
